name: CD - Production

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: false

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant Execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_ID }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_ID }}/timetoeat-server:latest .
          docker push ${{ secrets.DOCKERHUB_ID }}/timetoeat-server:latest

      - name: Copy configuration files to EC2
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "docker-compose.prod.yml,nginx/default.conf"
          target: "/home/ubuntu/TimeToEat"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            set -e
            cd /home/ubuntu/TimeToEat
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_ID }}" --password-stdin
            export COMPOSE_HTTP_TIMEOUT=1200
            
            # 느린 네트워크 대비: pull 재시도(최대 3회) + 병렬 끔
            i=0
            until [ $i -ge 3 ]; do
            if sudo docker compose -f docker-compose.prod.yml pull --no-parallel application; then
            break
            fi
            i=$((i+1))
            echo "pull 실패(${i}/3). 10초 후 재시도..."
            sleep 10
            done
      
            sudo docker compose -f docker-compose.prod.yml up -d --remove-orphans
            sudo docker image prune -f